### PR TITLE
Allow logging to a log file with a separate handler configuration

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
If this look good, I'll start adding some tests.

**Comment by The-Compiler** [comment]
I haven't tested it, but LGTM looking at the diff.

**Comment by s0undt3ch** [comment]
I would suggest merging this PR after #33(which I'll have to rebase).

**Comment by s0undt3ch** [comment]
Rebased to resolve conflicts

**Comment by s0undt3ch** [comment]
Rebased again to resolve conflicts.

Whats the status of this PR?

**Comment by eisensheng** [comment]
> Whats the status of this PR?

@s0undt3ch, can you rebase this PR on latest develop again, please? It seems some parts of this PR became redundant with the merge of #33.

**Comment by s0undt3ch** [comment]
Yes, I'll try to do it this evening.

**Comment by s0undt3ch** [comment]
PR rebased

**Comment by abusalimov** [comment]
Let's get this over with! =)

**Comment by s0undt3ch** [comment]
WooHoo!!!!

**Comment by s0undt3ch** [comment]
Thanks!

**Pull request merged**
