### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### eisensheng/pytest-catchlog now has a Chat Room on Gitter

@eisensheng has just created a chat room. You can visit it here: [https://gitter.im/eisensheng/pytest-catchlog](https://gitter.im/eisensheng/pytest-catchlog?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/eisensheng/pytest-catchlog?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by eisensheng** [comment]
I thought it might be a good idea to create a chatroom on Gitter for this project to informally discuss or announce some things. Please let me know what you think about this, @abusalimov, @The-Compiler.

**Comment by abusalimov** [comment]
Yeah, sure, why not. :shipit:

**Comment by The-Compiler** [comment]
-1 from me - see [Please don't use Slack for FOSS projects](https://drewdevault.com/2015/11/01/Please-stop-using-slack.html) for why, I think most of those points also hold true for gitter.

Why not just use the existing `#pylib` IRC channel where there are other pytest developers around as well?

**Comment by abusalimov** [comment]
They have an IRC bridge: https://irc.gitter.im/

**Comment by eisensheng** [comment]
> -1 from me - see Please don't use Slack for FOSS projects for why, I think most of those points also hold true for gitter.

Most of the criticized points indeed hold true for Gitter as well. I have to state beforehand that I'm a big fan of IRC myself and also supported freenode before in form of donations. I'm all in favour of open source solutions and would love to replace any proprietary/closed source solution where a superior FLOSS solution is available.

But there is one thing that Gitter solves so much better compared to IRC for example and that is persistently stored chat logs. This very valuable. Anyone can just simply drop a short line of text and it can be picked up by anyone else later on. Be it an unimportant question or just a notice. I know there is the possibility to host a Bouncer but anyone has to host it then in order to work like Gitter's stored chat logs. Or we set up botbot.me for the channel. But services like these are just another walled garden.

I'm also amused that nobody ever brings up XMPP in such a discussion. It has better support for File Transfer and somewhat modern Chat clients. Heck it even brings persistent chat logs and you can share files via HTTP by uploading them to the XMPP server. These XEPs are brand new. And it's open source. So if there would be something that could bring down Slack/Gitter/Hipchat then it would be a properly configured XMPP server with a modern client. But this is so rare you're better of with just giving up on that topic and resorting to email I guess.

**Pull request merged**
